version: 2.1

jobs:
  build:
    macos:
      xcode: 15.2.0 

    steps:
      # Checkout the code as the first step.
      - checkout
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

  danger_job:
    steps:
      - git_config_step
      - macos/install-rosetta
      - run:
          name: Bundle Install Step
          command: bundle install 
      - run:
          name: Install Danger-Swift
          command: brew install danger/tap/danger-swift
      - run:
          name: Which Danger
          command: 'which danger-swift'  
      - run:
          name: Run Danger
          command: 'danger-swift ci'          

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
