version: 2.1

orbs:
  node: circleci/node@4.7.0
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2
  ruby: circleci/ruby@1.2.0
  
container_medium: &container_medium
  macos:
    xcode: 14.2.0
  resource_class: medium
  
jobs:
  danger_job:
    <<: *container_medium
    steps:
      - checkout
      - macos/install-rosetta
      - run:
          name: Bundle Install Step
          command: bundle install 
      - run:
          name: Install Danger-Swift
          command: brew install danger/tap/danger-swift
      - run:
          name: Which Danger
          command: 'which danger-swift'  
      - run:
          name: Run Danger
          command: 'danger-swift ci'          

workflows:
  version: 2.1
  build-and-release-workflow:
    jobs:
      - danger_job
