version: 2.1

orbs:
  node: circleci/node@4.7.0
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2
  ruby: circleci/ruby@1.2.0
  
container_medium: &container_medium
  macos:
    xcode: 14.2.0
  
jobs:
  danger_job:
    <<: *container_medium
    steps:
      - checkout
      - run:
          name: Install Rosetta
          command: softwareupdate --install-rosetta --agree-to-license
      # - run:
      #     name: Bundle Install Step
      #     command: bundle install 
      - run:
          name: Install Danger-Swift
          command: brew install danger/tap/danger-swift
      - run:
          name: Which Danger
          command: 'which danger-swift'
      - run:
          name: Danger Version
          command: 'danger --version'          
      - run:
          name: Danger Swift Version
          command: 'danger-swift --version'
      - run:
          name: Danger Token Check
          command: |
            if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then
              echo "Running danger"
            else
              echo "Not running danger because $DANGER_GITHUB_API_TOKEN is not found"
            fi          
      - run:
          name: Run Danger CI
          command: 'danger-swift ci --verbose'       

workflows:
  version: 2.1
  build-and-release-workflow:
    jobs:
      - danger_job
