name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/swift@3.3.0
        with:
            args: --failOnErrors --no-publish-check
