name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/swift@3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.Dan }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        with:
            args: --failOnErrors --no-publish-check
